### ISSUE TITLE
潮语 | Chromium

### ISSUE THREAD

**Issue by Challestend** [Challestend/Challestend.github.io#32]
https://challestend.github.io/chaoyu/ 

 概述《潮语》是潮子的语录结集，由潮子弟子及再传弟子编写而成，至9012年前期成书。全书共$+\infty$篇$+\infty$章，以语录体为主，叙事体为辅，主要记录潮子的言行，较为集中地体现了潮子的政治主张、伦理思想、道德观念及教育原则等。此书是潮家学派的经典著作之一，与《大潮》《潮队长金句名言》《潮子》并称「四书」，再加上《2019~9012年IOI第一名潮爷自传》《潮爷算法导论》《如何向潮爷一

**Comment by dftyem** [comment]
围观潮学现场

**Comment by dftyem** [comment]
**我来测试markdown**

**Comment by stevebraveman** [comment]
潮学の学习

**Comment by ColorfulMist** [comment]
天文学更好

**Comment by first-speaker** [comment]
？？？和我啥关系？

**Comment by ctz45562** [comment]
催更
