### ISSUE TITLE
更新日志 | Chromium

### ISSUE THREAD

**Issue by Challestend** [Challestend/Challestend.github.io#33]
https://challestend.github.io/log/ 

 直角，这是这篇blog的更新日志。 不过我不是一个考虑周全的人，之前9月份搭起博客时，我并没有考虑到这些。因而，之前的很多更新的具体时间已经无从知晓。  2018-09-27 建站。   （略） 2018-12-13 令theme-next-pace的加载进度条的颜色温和了一点。 将hexo-symbols-count-time的字数和时间统计替换成了精确数值。 减少了侧边栏和网易云外链的宽度。

**Comment by Challestend** [comment]
评论系统换成Gitalk啦w

**Comment by Challestend** [comment]
[__Play__ _with_ ~~markdown~~.](FAQ!)

**Comment by ctz45562** [comment]
成爷怎么把东方删了啊（
